### ISSUE TITLE
Need to load javascript backend: the simple blog example doesn't work out of the box

### ISSUE THREAD

**Issue by vindarel** [weblocks-framework/weblocks-examples#5]
Hi,

I tried the simple blog example:

    (ql:quickload :weblocks-demo)
    (weblocks-demo:start-weblocks-demo)
    
but I get this error message:

> Please load javascript backend for framework (default is :prototype from https://github.com/html/weblocks-prototype-js) and pass :js-backend value (`:js-backend :prototype` for example) into your `defwebapp`

the error message looks good, but the example doesn't work out of the box.

Thanks for those examples.

**Comment by wislin** [comment]
I also get the same error. weblock-demo can not works.

**Comment by vindarel** [comment]
Did you see the new Weblock's quickstart ? http://40ants.com/weblocks/quickstart.html It features a todo-app. (It is developed in another repository: https://github.com/40ants/weblocks and AFAIK it will eventually become the official one)

**Comment by vindarel** [comment]
No, because this repository is about the old Weblocks, and I'll focus on the one being worked on.
